### ISSUE TITLE
DRC violations in GF018green_ipio_5p0c_75_3lm

### ISSUE THREAD

**Issue by mkkassem** [google/globalfoundries-pdk-libs-gf180mcu_fd_io#6] opened 2022-11-08 21:21 UTC
DRC violations in GF018green_ipio_5p0c_75_3lm vs. documented rule in the design manual

## DF.1a
<img width="1584" alt="Screenshot 2022-11-08 at 1 18 02 PM" src="https://user-images.githubusercontent.com/2908302/200677731-2dbc3916-bfe3-4724-8a02-90ad2feaabbc.png">

## DF.14
<img width="1569" alt="Screenshot 2022-11-08 at 1 18 13 PM" src="https://user-images.githubusercontent.com/2908302/200678106-bb013246-dd04-4b3e-99bc-37c398a115f2.png">

**Comment by RTimothyEdwards** [comment] 2022-11-08 22:37
Not a bug.  The cell is a 0.75um wide I/O filler cell and can only be properly checked for DRC in the full context of a padframe ring, since it must abut other padframe cells on either side which resolve the DRC errors.

**Comment by mkkassem** [comment] 2022-11-10 10:34
@atorkmabrains please see comment from @RTimothyEdwards

**Comment by atorkmabrains** [comment] 2022-11-10 18:31
@RTimothyEdwards Great. If that's the case that's fine, but keep in mind that we are testing each cell on it's own. And yes, as you said some of them might be used in that way.

**Comment by atorkmabrains** [comment] 2023-04-10 00:23
@RTimothyEdwards and @mkkassem No longer needed. Will close the issue.

**Closed as completed by atorkmabrains** 2023-04-10 00:23 UTC
Labels: bug
